In [2]:
# !pip install numpy
# !pip install pandas

In [3]:
import numpy as np
import pandas as pd

/tmp/ipykernel_5772/3269992828.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
df=pd.read_csv("Dataset\\Sample Productivity Data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Dataset\\Sample Productivity Data.csv'

In [14]:
df.head()

,Client_Code,EmployeeID,DOJ,Gender,Production,Target,Date,Tool,Manager,Vertical,Vertical_Head
0,1,32442,3/19/2019,Male,21,40,3/23/2020,New Tool,M-1,C,Makarand
1,1,38741,12/24/2019,Male,37,40,3/23/2020,New Tool,M-1,C,Makarand
2,1,38665,12/20/2019,Male,22,40,3/23/2020,New Tool,M-1,C,Makarand
3,1,35562,8/14/2019,Male,31,40,3/23/2020,New Tool,M-1,C,Makarand
4,1,30690,11/19/2018,Male,40,40,3/23/2020,New Tool,M-1,C,Makarand

In [20]:
df.describe()

         Client_Code     EmployeeID     Production    Target
count  171068.000000  171068.000000  171068.000000  171068.0
mean       20.472789   38545.728073      29.823105      40.0
std        16.572826   16263.454230      25.908702       0.0
min         1.000000    1254.000000       0.000000      40.0
25%         8.000000   31115.000000      16.000000      40.0
50%        15.000000   35136.000000      25.000000      40.0
75%        32.000000   38214.000000      36.000000      40.0
max        81.000000  100758.000000    1205.000000      40.0

In [27]:
df["Gender"].value_counts()

Gender
Male      133360
Female     37708
Name: count, dtype: int64

In [28]:
for column in df.columns:
    value_counts = df[column].value_counts()
    print(f"Column: {column}")
    print(value_counts)
    print()

Column: Client_Code
Client_Code
9     14573
1     13856
12    12470
8      9445
15     9237
      ...
81        2
75        1
36        1
68        1
80        1
Name: count, Length: 81, dtype: int64

Column: EmployeeID
EmployeeID
32857    213
31421    213
35564    211
29644    209
36105    209
        ...
37461      1
38028      1
37980      1
37999      1
41673      1
Name: count, Length: 2500, dtype: int64

Column: DOJ
DOJ
10/10/2018    4169
10/21/2019    3414
9/5/2019      3324
11/15/2018    3293
1/15/2020     3196
              ...
10/13/2016       1
3/21/2014        1
4/15/2013        1
9/1/2017         1
7/3/2014         1
Name: count, Length: 442, dtype: int64

Column: Gender
Gender
Male      133360
Female     37708
Name: count, dtype: int64

Column: Production
Production
30     7879
20     6847
25     5497
23     5353
31     4826
       ...
415       1
322       1
364       1
252       1
314       1
Name: count, Length: 363, dtype: int64

Column: Target
Target
40    171068
Name: count, dtype: int64

Column: Date
Date
7/28/2020     1125
7/30/2020     1120
7/29/2020     1119
7/22/2020     1116
7/23/2020     1088
              ...
1/2/2021         3
11/29/2020       2
11/15/2020       2
12/6/2020        1
12/27/2020       1
Name: count, Length: 295, dtype: int64

Column: Tool
Tool
Old Tool    125254
New Tool     45814
Name: count, dtype: int64

Column: Manager
Manager
M-1    35536
M-2    34168
M-3    23234
M-4    18878
M-7    16354
M-5    15028
M-9    13948
M-6     9857
M-8     4065
Name: count, dtype: int64

Column: Vertical
Vertical
C    92553
D    32578
B    29299
A    16638
Name: count, dtype: int64

Column: Vertical_Head
Vertical_Head
Makarand    92553
Rahul       32578
Subhash     29299
Shweta      16638
Name: count, dtype: int64